version: '3'
services:

  o2a-sta-harvester:
    image: speckij/o2a-sta-harvester:0.0.5-UFZ-DEMO
    depends_on:
     - sta
    environment:
      LOGGING_LEVEL_ORG_N52: INFO

  sta:
    image: speckij/sta-private:3.1.1-UFZ-DEMO
    # build: https://github.com/52North/sensorweb-server-sta.git#develop
    ports:
     - 8081:8081
#    - 1883:1883
#    - 8883:8883
    environment:
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_ORG_N52: INFO
#      SPRING_DATASOURCE_URL: jdbc:postgresql://sta-postgresdb:5432/sta
#      SPING_JPA_PROPERTIES_HIBERNATE_HBM2DDL: update
#      MQTT_BROKER_PLAINTCP_ENABLED: "false"
#      MQTT_BROKER_WEBSOCKET_ENABLED: "false"
#      MQTT_BROKER_PERSISTENCE_ENABLED: "false"
#      SERVER_ROOT_URL: http://207.154.210.84:80/v1.1/
#      SERVER_SERVLET_CONTEXT_PATH: /v1.1
#      SERVER_FEATURE_UPDATEFOI: "false"
#      SERVER_FEATURE_MQTTPUBLISHTOPICS: Observations
#      SERVER_FEATURE_VARIABLEENCODINGTYPE: "false"
#      SERVER_FEATURE_ISMOBILE: "false"
    restart: on-failure:10
    depends_on:
    - sta-postgresdb


  caddy:
    image: caddy:2
    ports:
    - 80:80
    - 443:443
    volumes:
    - caddy-data:/data
    - ./Caddyfile:/etc/caddy/Caddyfile

  sta-postgresdb:
    image: postgis/postgis:12-master
    labels:
      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
      - "org.52north.context=ufz-2020-R25244"
      - "org.52north.end-of-life=2021-12-31T00:00:00Z"
    restart: on-failure
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      - POSTGRES_DB=sta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis

    # For debug/show purposes!
    ports:
      - 5000:5432
  
  grafana:
    image: grafana/grafana
    labels:
      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
      - "org.52north.context=ufz-2020-R25244"
      - "org.52north.end-of-life=2021-12-31T00:00:00Z"
    restart: on-failure
    environment:
      GF_INSTALL_PLUGINS: grafana-worldmap-panel,grafana-clock-panel,briangann-datatable-panel,https://github.com/panodata/grafana-map-panel/releases/download/0.15.0/grafana-map-panel-0.15.0.zip;grafana-map-panel,marcusolsson-dynamictext-panel
#      GF_SERVER_ROOT_URL: "http://localhost/dashboard/"
#      GF_SERVE_FROM_SUB_PATH: "true"
    ports:
      - 3000:3000
    volumes:
      - /home/specki/git/sta-grafana:/var/lib/grafana/plugins/sta-grafana
      - /home/specki/git/alexandra-trackmap-panel:/var/lib/grafana/plugins/alexandra-trackmap-panel

#  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
#    labels:
#      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
#      - "org.52north.context=ufz-2020-R25244"
#      - "org.52north.end-of-life=2021-12-31T00:00:00Z"
#
#    volumes:
#      - elastic-data:/usr/share/elasticsearch/data
#    environment:
#      discovery.type: single-node
#    ports:
#      - 9200:9200
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    restart: unless-stopped
#    healthcheck:
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      test: |
#        status=$$(curl -f -s localhost:9200/_cat/health?h=status) && [ "$$status" == "green" -o "$$status" == "yellow" ] && exit 0 || exit 1
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.10.1
#    labels:
#      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
#      - "org.52north.context=ufz-2020-R25244"
#      - "org.52north.end-of-life=2021-12-31T00:00:00Z"
#    environment:
#      ELASTICSEARCH_HOSTS: http://elastic:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - elastic
#    healthcheck:
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      test: curl -sf http://localhost:5601/api/status
#
#  filebeat:
#    image: docker.elastic.co/beats/filebeat:7.10.1
#    labels:
#      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
#      - "org.52north.context=ufz-2020-R25244"
#      - "org.52north.end-of-life=2021-12-31T00:00:00Z"
#    user: root
#    environment:
#      ELASTICSEARCH_HOSTS: http://elastic:9200
#    volumes:
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
#      - ./ilm.json:/usr/share/filebeat/ilm.json
#    command: ["-strict.perms=false"]
#    depends_on:
#      - elastic
#    healthcheck:
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      test: filebeat test output
#    restart: unless-stopped

volumes:
  elastic-data:
    labels:
      - "org.n52.backup=false"
    driver: local
  caddy-data:
    labels:
      - "org.n52.backup=false"
    driver: local

