version: '3'
services:
#  sta:
#  image: 52north/sensorweb-server-sta:3.0.0
#  # build: https://github.com/52North/sensorweb-server-sta.git#develop
#  ports:
#    - 8081:8081
#    - 1883:1883
#    - 8883:8883
#  environment:
#    LOGGING_LEVEL_ROOT: INFO
#     LOGGING_LEVEL_ORG_N52: TRACE
#     SPRING_DATASOURCE_URL: jdbc:postgresql://sta-postgresdb:5432/sta
#     SPING_JPA_PROPERTIES_HIBERNATE_HBM2DDL: update
#     MQTT_BROKER_PLAINTCP_ENABLED: "true"
#     MQTT_BROKER_WEBSOCKET_ENABLED: "true"
#     MQTT_BROKER_PERSISTENCE_ENABLED: "false"
#     SERVER_ROOTURL: http://localhost:8081/sta/
#     SERVER_SERVLET_CONTEXT_PATH: /sta
#     SERVER_FEATURE_UPDATEFOI: "false"
#     SERVER_FEATURE_MQTTPUBLISHTOPICS: Observations
#      SERVER_FEATURE_VARIABLEENCODINGTYPE: "false"
#      SERVER_FEATURE_ISMOBILE: "false"
#    restart: on-failure:10
#    depends_on:
#    - sta-postgresdb

  sta-postgresdb:
    image: postgis/postgis:12-master
    labels:
      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
      - "org.52north.context=ufz-2020-R25244"
      - "org.52north.end-of-life=2021-12-31T00:00:00Z"
    restart: on-failure
    environment:
      - POSTGRES_DB=sta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis

    # For debug/show purposes!
    ports:
      - 5000:5432
  
  grafana:
    image: grafana/grafana
    labels:
      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
      - "org.52north.context=ufz-2020-R25244"
      - "org.52north.end-of-life=2021-12-31T00:00:00Z"
    restart: on-failure
    ports:
      - 3000:3000

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    labels:
      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
      - "org.52north.context=ufz-2020-R25244"
      - "org.52north.end-of-life=2021-12-31T00:00:00Z"

    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: |
        status=$$(curl -f -s localhost:9200/_cat/health?h=status) && [ "$$status" == "green" -o "$$status" == "yellow" ] && exit 0 || exit 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    labels:
      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
      - "org.52north.context=ufz-2020-R25244"
      - "org.52north.end-of-life=2021-12-31T00:00:00Z"
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - 5601:5601
    depends_on:
      - elastic
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: curl -sf http://localhost:5601/api/status

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    labels:
      - "org.52north.contact=j.speckamp+ufz-2020-demoserver@52north.org"
      - "org.52north.context=ufz-2020-R25244"
      - "org.52north.end-of-life=2021-12-31T00:00:00Z"
    user: root
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./ilm.json:/usr/share/filebeat/ilm.json
    command: ["-strict.perms=false"]
    depends_on:
      - elastic
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: filebeat test output
    restart: unless-stopped

volumes:
  elastic-data:
    labels:
      - "org.n52.backup=false"
    driver: local
