
spring:
  codec:
    max-in-memory-size: 100MB
  main:
    web-environment: false


server:
  port: ${random.int(5010,5100)}
  config:
    staURL: "https://sta:8081/v1.1/"


logging:
  level:
    org:
      n52: TRACE
    reactor:
      netty:
        http:
#          client: DEBUG
